name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    timeout-minutes: 120
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: wakatime-internal/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
